# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Aspect.create!([
  {aspect: "Aer", keywords: "air", component1: "Primal", component2: "", sources: "tall plants (notably sugar cane), many compounds"},
  {aspect: "Alienis", keywords: "eldritch", component1: "Tenebrae", component2: "Vacuous", sources: "ender pearls"},
  {aspect: "Aqua", keywords: "water", component1: "Primal", component2: "", sources: "cactus, sugar cane, Gelum, Victus, Limus"},
  {aspect: "Arbor", keywords: "tree", component1: "Aer", component2: "Herba", sources: "logs (greatwood and silverwood are not perfect), any wooden items"},
  {aspect: "Auram", keywords: "aura", component1: "Aer", component2: "Praecantatio", sources: "ethereal essence"},
  {aspect: "Bestia", keywords: "animal", component1: "Motus", component2: "Victus", sources: "raw meat, eggs, spider eyes, Corpus, Humanus"},
  {aspect: "Cognitio", keywords: "mind", component1: "Ignis", component2: "Spiritus", sources: "paper, zombie brains, Humanus"},
  {aspect: "Corpus", keywords: "flesh", component1: "Bestia", component2: "Mortuus", sources: "rotten flesh, all meat"},
  {aspect: "Exanimis", keywords: "undead", component1: "Motus", component2: "Mortuus", sources: "zombie brains, ghast tears"},
  {aspect: "Fabrico", keywords: "craft, repair", component1: "Humanus", component2: "Instrumentum", sources: "crafting tables, cooked meats, wool"},
  {aspect: "Fames", keywords: "hunger", component1: "Vacuos", component2: "Victus", sources: "melon slices, meat nuggets, cooked food"},
  {aspect: "Herba", keywords: "plant", component1: "Terra", component2: "Victus", sources: "wheat seeds, pumpkin seeds, vines, nether wart, most plants, Arbor, Messis"},
  {aspect: "Gelum", keywords: "cold, ice", component1: "Ignis", component2: "Perditio", sources: "snowballs, snow blocks"},
  {aspect: "Humanus", keywords: "human", component1: "Bestia", component2: "Cognitio", sources: "rotten flesh, Fabrico, Instrumentum, Messis"},
  {aspect: "Ignis", keywords: "fire", component1: "Primal", component2: "", sources: "coal/charcoal, gunpowder, Cognitio, Gelum, Potentia, Telum"},
  {aspect: "Instrumentum", keywords: "tool", component1: "Humanus", component2: "Ordo", sources: "flint, shovels, axes, several compounds"},
  {aspect: "Iter", keywords: "travel", component1: "Motus", component2: "Terra", sources: "boats, ender pearls"},
  {aspect: "Limus", keywords: "slime", component1: "Aqua", component2: "Victus", sources: "slimeballs, eggs, tainted goo"},
  {aspect: "Lucrum", keywords: "greed, wealth", component1: "Fames", component2: "Humanus", sources: "gold, emeralds, gold coins, gold items"},
  {aspect: "Lux", keywords: "light", component1: "Aer", component2: "Ignis", sources: "torches, Tenebrae"},
  {aspect: "Machina", keywords: "machine, device", component1: "Instrumentum", component2: "Motus", sources: "buttons, redstone, other devices"},
  {aspect: "Messis", keywords: "crop", component1: "Herba", component2: "Humanus", sources: "pumpkins, wheat, other crops"},
  {aspect: "Metallum", keywords: "metal", component1: "Terra", component2: "Vitreus", sources: "metal nuggets, metallic items"},
  {aspect: "Meto", keywords: "harvest", component1: "Instrumentum", component2: "Messis", sources: "hoes"},
  {aspect: "Mortuus", keywords: "death", component1: "Perditio", component2: "Victus", sources: "bones, Corpus, Spiritus"},
  {aspect: "Motus", keywords: "motion", component1: "Aer", component2: "Ordo", sources: "trapdoors, Bestia, Machina, Volatus"},
  {aspect: "Ordo", keywords: "order", component1: "Primal", component2: "", sources: "silverwood logs, smooth sandstone, many compounds, Instrumentum, Motus, Potentia"},
  {aspect: "Pannus", keywords: "cloth", component1: "Bestia", component2: "Instrumentum", sources: "string, wool, leather"},
  {aspect: "Perditio", keywords: "Chaos", component1: "Primal", component2: "", sources: "cobblestone, cactus, gunpowder, Gelum, Mortuus, Vitium"},
  {aspect: "Perfodio", keywords: "mining", component1: "Humanus", component2: "Terra", sources: "pickaxes"},
  {aspect: "Permutatio", keywords: "exchange", component1: "Ordo", component2: "Perditio", sources: "quicksilver, droppers, dispensers"},
  {aspect: "Potentia", keywords: "energy", component1: "Ignis", component2: "Ordo", sources: "coal/charcoal, Praecantatio"},
  {aspect: "Praecantatio", keywords: "magic", component1: "Potentia", component2: "Vacuous", sources: "greatwood logs, silverwood logs, chiseled sandstone, nether wart, magical items"},
  {aspect: "Sano", keywords: "healing", component1: "Ordo", component2: "Victus", sources: "cake, healing potions, regeneration potions"},
  {aspect: "Sensus", keywords: "senses", component1: "Aer", component2: "Spiritus", sources: "most dyes, carrots"},
  {aspect: "Spiritus", keywords: "soul", component1: "Mortuus", component2: "Victus", sources: "soul sand, ghast tears, Cognitio, Sensus"},
  {aspect: "Telum", keywords: "weapon", component1: "Ignis", component2: "Instrumentum", sources: "arrows, weapons"},
  {aspect: "Tempestas", keywords: "weather", component1: "Aer", component2: "Aqua", sources: "mana beans, ethereal essence"},
  {aspect: "Tenebrae", keywords: "darkness", component1: "Lux", component2: "Perditio", sources: "mushrooms, obsidian"},
  {aspect: "Terra", keywords: "earth, ground", component1: "Primal", component2: "", sources: "dirt, smooth stone, potatoes, cobblestone, many compounds like Victus"},
  {aspect: "Tutamen", keywords: "armor", component1: "Instrumentum", component2: "Terra", sources: "leather, armor"},
  {aspect: "Vacuos", keywords: "void", component1: "Aer", component2: "Perditio", sources: "wooden bowls, Fames, Praecantatio"},
  {aspect: "Venenum", keywords: "poison", component1: "Aqua", component2: "Perditio", sources: "quicksilver, spider eyes"},
  {aspect: "Victus", keywords: "life", component1: "Aqua", component2: "Terra", sources: "eggs, raw meat, Bestia, Fames, Herba, Mortuus."},
  {aspect: "Vinculum", keywords: "life", component1: "Motus", component2: "Perditio", sources: "soul sand, amber"},
  {aspect: "Vitium", keywords: "taint", component1: "Perditio", component2: "Praecantatio", sources: "tainted goo, taintacles"},
  {aspect: "Vitreus", keywords: "crystal", component1: "Ordo", component2: "Terra", sources: "glass, diamonds, emeralds, Metallum"},
  {aspect: "Volatus", keywords: "flight", component1: "Aer", component2: "Motus", sources: "feathers"}
])
